import logistic_regression as lr
def compress_features(dataset):
    dataset.replace('Without-pay', 'Unemployed',inplace=True)
    dataset.replace('Never-worked', 'Unemployed',inplace=True)
    dataset.replace('Local-gov', 'State_gov',inplace=True)
    dataset.replace('State-gov', 'State_gov',inplace=True)
    dataset.replace('Self-emp-inc', 'Self_employed',inplace=True)
    dataset.replace('Self-emp-not-inc', 'Self_employed',inplace=True)
    dataset.replace(['Divorced', 'Married-AF-spouse', 'Married-civ-spouse', 'Married-spouse-absent',  'Never-married','Separated'],['divorced','married','married','married','not_married','divorced'],inplace=True)
    dataset.replace(['11th','9th',' 7th-8th', '12th', '1st-4th', '10th','5th-6th', 'Preschool'],['School','School','School','School','School','School','School','School'],inplace=True)
    dataset.replace(["Canada", "Cuba", "Dominican-Republic", "El-Salvador", "Guatemala","Haiti", "Honduras", "Jamaica", "Mexico", "Nicaragua", "Outlying-US(Guam-USVI-etc)", "Puerto-Rico", "Trinadad&Tobago","United-States"],14*['North_America'],inplace=True)
    dataset.replace(["Cambodia", "China", "Hong", "India", "Iran", "Japan", "Laos","Philippines", "Taiwan", "Thailand", "Vietnam"],11*['Asia'],inplace=True)
    dataset.replace(["England", "France", "Germany", "Greece", "Holand-Netherlands","Hungary", "Ireland", "Italy", "Poland", "Portugal", "Scotland","Yugoslavia"],12*['Europe'],inplace=True)
    dataset.replace(["Columbia", "Ecuador", "Peru"],3*["South_America"])
if (__name__ == "__main__"):
    lr_model=lr.logistic_regression()
    dataset=lr.pd.read_csv('./q2_train.csv')
    compress_features(dataset)
    dataset = lr.pd.get_dummies(dataset, prefix_sep='_', drop_first=True)
    print(len(dataset.columns))